CREATE TABLE canonical_sleep_summaries
(
    id                INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date              DATE        NOT NULL,
    source_instance_id INTEGER    NOT NULL REFERENCES source_instances (id),
    sleep_summary_id  INTEGER     NOT NULL REFERENCES sleep_summaries (id) ON DELETE CASCADE,
    start_at          TIMESTAMPTZ NOT NULL,
    end_at            TIMESTAMPTZ NOT NULL,
    algorithm_version INTEGER     NOT NULL,
    computed_at       TIMESTAMPTZ NOT NULL,
    UNIQUE (date, sleep_summary_id, algorithm_version),
    CHECK (start_at < end_at),
    CHECK (algorithm_version > 0)
);

CREATE INDEX canonical_sleep_summaries_date_start_idx
    ON canonical_sleep_summaries (date, start_at);

CREATE INDEX canonical_sleep_summaries_source_date_idx
    ON canonical_sleep_summaries (source_instance_id, date);
