CREATE TABLE canonical_sleep_sessions
(
    id                INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date              DATE        NOT NULL,
    source_instance_id INTEGER    NOT NULL REFERENCES source_instances (id),
    sleep_session_id  INTEGER     NOT NULL REFERENCES sleep_sessions (id) ON DELETE CASCADE,
    start_at          TIMESTAMPTZ NOT NULL,
    end_at            TIMESTAMPTZ NOT NULL,
    algorithm_version INTEGER     NOT NULL,
    computed_at       TIMESTAMPTZ NOT NULL,
    UNIQUE (date, sleep_session_id, algorithm_version),
    CHECK (start_at < end_at),
    CHECK (algorithm_version > 0)
);

CREATE INDEX canonical_sleep_sessions_date_start_idx
    ON canonical_sleep_sessions (date, start_at);

CREATE INDEX canonical_sleep_sessions_source_date_idx
    ON canonical_sleep_sessions (source_instance_id, date);

CREATE TABLE canonical_step_daily_summaries
(
    id                    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date                  DATE        NOT NULL,
    source_instance_id    INTEGER     NOT NULL REFERENCES source_instances (id),
    step_daily_summary_id INTEGER     NOT NULL REFERENCES step_daily_summaries (id) ON DELETE CASCADE,
    steps                 INTEGER     NOT NULL,
    algorithm_version     INTEGER     NOT NULL,
    computed_at           TIMESTAMPTZ NOT NULL,
    UNIQUE (date, algorithm_version),
    CHECK (steps >= 0),
    CHECK (algorithm_version > 0)
);

CREATE INDEX canonical_step_daily_summaries_source_date_idx
    ON canonical_step_daily_summaries (source_instance_id, date);

CREATE TABLE canonical_activity_summaries
(
    id                  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date                DATE        NOT NULL,
    source_instance_id  INTEGER     NOT NULL REFERENCES source_instances (id),
    activity_summary_id INTEGER     NOT NULL REFERENCES activity_summaries (id) ON DELETE CASCADE,
    algorithm_version   INTEGER     NOT NULL,
    computed_at         TIMESTAMPTZ NOT NULL,
    UNIQUE (date, algorithm_version),
    CHECK (algorithm_version > 0)
);

CREATE INDEX canonical_activity_summaries_source_date_idx
    ON canonical_activity_summaries (source_instance_id, date);
