-- Collapse the six point-in-time scalar metric tables (heart_rate_samples,
-- respiratory_rate_samples, hrv_samples, body_measurements, cardiovascular_measurements,
-- extended_body_measurements) into one generic scalar_samples table, and replace their
-- eagerly materialized canonical tables with a read-time view. The Kotlin
-- ScalarMetricRegistry is the source of truth for metric_catalog and provider_ranks;
-- this seed only has to be complete enough for the backfill below.

CREATE TABLE metric_catalog
(
    metric_type      TEXT PRIMARY KEY,
    family           TEXT             NOT NULL,
    unit             TEXT             NOT NULL,
    min_value        DOUBLE PRECISION,
    max_value        DOUBLE PRECISION,
    supports_segment BOOLEAN          NOT NULL DEFAULT FALSE
);

CREATE TABLE provider_ranks
(
    family        TEXT    NOT NULL,
    provider_code TEXT    NOT NULL,
    rank          INTEGER NOT NULL,
    PRIMARY KEY (family, provider_code)
);

INSERT INTO metric_catalog (metric_type, family, unit, min_value, max_value, supports_segment)
VALUES ('heart_rate', 'heart_rate', 'bpm', 25, 250, FALSE),
       ('respiratory_rate', 'respiratory_rate', 'breaths_per_minute', 5, 80, FALSE),
       ('hrv_rmssd', 'hrv', 'ms', 0, 500, FALSE),
       ('weight', 'body_measurement', 'kg', 0, NULL, FALSE),
       ('body_fat', 'body_measurement', 'percent', 0, 100, FALSE),
       ('muscle', 'body_measurement', 'kg', 0, NULL, FALSE),
       ('water', 'body_measurement', 'percent', 0, 100, FALSE),
       ('visceral_fat', 'body_measurement', 'rating', 0, NULL, FALSE),
       ('fat_mass', 'body_measurement', 'kg', 0, NULL, FALSE),
       ('fat_free_mass', 'body_measurement', 'kg', 0, NULL, FALSE),
       ('bone_mass', 'body_measurement', 'kg', 0, NULL, FALSE),
       ('intracellular_water', 'body_measurement', 'kg', 0, NULL, FALSE),
       ('extracellular_water', 'body_measurement', 'kg', 0, NULL, FALSE),
       ('basal_metabolic_rate', 'body_measurement', 'kcal', 0, NULL, FALSE),
       ('segmental_fat_mass', 'body_measurement', 'kg', 0, NULL, TRUE),
       ('segmental_muscle_mass', 'body_measurement', 'kg', 0, NULL, TRUE),
       ('segmental_fat_free_mass', 'body_measurement', 'kg', 0, NULL, TRUE),
       ('pulse_wave_velocity', 'cardiovascular', 'm/s', 0, NULL, FALSE),
       ('vascular_age', 'cardiovascular', 'years', 0, NULL, FALSE),
       ('standing_heart_rate', 'cardiovascular', 'bpm', 0, NULL, FALSE);

INSERT INTO provider_ranks (family, provider_code, rank)
VALUES ('steps', 'google_health', 0),
       ('steps', 'health_connect', 1),
       ('steps', 'withings', 2),
       ('activity', 'google_health', 0),
       ('activity', 'health_connect', 1),
       ('activity', 'withings', 2),
       ('sleep', 'withings', 0),
       ('sleep', 'google_health', 1),
       ('sleep', 'health_connect', 2),
       ('sleep_summary', 'withings', 0),
       ('sleep_summary', 'google_health', 1),
       ('sleep_summary', 'health_connect', 2),
       ('body_measurement', 'withings', 0),
       ('body_measurement', 'google_health', 1),
       ('body_measurement', 'health_connect', 2),
       ('heart_rate', 'google_health', 0),
       ('heart_rate', 'health_connect', 1),
       ('heart_rate', 'withings', 2),
       ('respiratory_rate', 'withings', 0),
       ('respiratory_rate', 'google_health', 1),
       ('respiratory_rate', 'health_connect', 2),
       ('hrv', 'withings', 0),
       ('hrv', 'google_health', 1),
       ('hrv', 'health_connect', 2),
       ('cardiovascular', 'withings', 0),
       ('cardiovascular', 'google_health', 1),
       ('cardiovascular', 'health_connect', 2);

CREATE TABLE scalar_samples
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_instance_id  INTEGER          NOT NULL REFERENCES source_instances (id),
    ingestion_record_id INTEGER REFERENCES ingestion_records (id),
    provider_record_id  TEXT,
    measured_at         TIMESTAMPTZ      NOT NULL,
    metric_type         TEXT             NOT NULL REFERENCES metric_catalog (metric_type),
    value               DOUBLE PRECISION NOT NULL,
    unit                TEXT             NOT NULL,
    context             TEXT,
    segment             TEXT,
    created_at          TIMESTAMPTZ      NOT NULL
);

CREATE UNIQUE INDEX scalar_samples_provider_record_uq
    ON scalar_samples (source_instance_id, provider_record_id, metric_type, COALESCE(segment, ''))
    WHERE provider_record_id IS NOT NULL;

CREATE INDEX scalar_samples_metric_measured_idx
    ON scalar_samples (metric_type, measured_at, id);

CREATE INDEX scalar_samples_source_metric_measured_idx
    ON scalar_samples (source_instance_id, metric_type, measured_at);

-- Backfill from the six legacy tables.
INSERT INTO scalar_samples (source_instance_id, ingestion_record_id, provider_record_id,
                            measured_at, metric_type, value, unit, context, segment, created_at)
SELECT source_instance_id,
       ingestion_record_id,
       provider_record_id,
       measured_at,
       'heart_rate',
       bpm::double precision,
       'bpm',
       context,
       NULL,
       created_at
FROM heart_rate_samples
ON CONFLICT DO NOTHING;

INSERT INTO scalar_samples (source_instance_id, ingestion_record_id, provider_record_id,
                            measured_at, metric_type, value, unit, context, segment, created_at)
SELECT source_instance_id,
       ingestion_record_id,
       provider_record_id,
       measured_at,
       'respiratory_rate',
       breaths_per_minute::double precision,
       'breaths_per_minute',
       context,
       NULL,
       created_at
FROM respiratory_rate_samples
ON CONFLICT DO NOTHING;

INSERT INTO scalar_samples (source_instance_id, ingestion_record_id, provider_record_id,
                            measured_at, metric_type, value, unit, context, segment, created_at)
SELECT source_instance_id,
       ingestion_record_id,
       provider_record_id,
       measured_at,
       'hrv_' || metric_type,
       value,
       unit,
       context,
       NULL,
       created_at
FROM hrv_samples
ON CONFLICT DO NOTHING;

INSERT INTO scalar_samples (source_instance_id, ingestion_record_id, provider_record_id,
                            measured_at, metric_type, value, unit, context, segment, created_at)
SELECT source_instance_id,
       ingestion_record_id,
       provider_record_id,
       measured_at,
       metric_type,
       value,
       unit,
       NULL,
       NULL,
       created_at
FROM body_measurements
ON CONFLICT DO NOTHING;

INSERT INTO scalar_samples (source_instance_id, ingestion_record_id, provider_record_id,
                            measured_at, metric_type, value, unit, context, segment, created_at)
SELECT source_instance_id,
       ingestion_record_id,
       provider_record_id,
       measured_at,
       metric_type,
       value,
       unit,
       NULL,
       NULL,
       created_at
FROM cardiovascular_measurements
ON CONFLICT DO NOTHING;

INSERT INTO scalar_samples (source_instance_id, ingestion_record_id, provider_record_id,
                            measured_at, metric_type, value, unit, context, segment, created_at)
SELECT source_instance_id,
       ingestion_record_id,
       provider_record_id,
       measured_at,
       metric_type,
       value,
       unit,
       NULL,
       segment,
       created_at
FROM extended_body_measurements
ON CONFLICT DO NOTHING;

DROP TABLE canonical_heart_rate_samples;
DROP TABLE canonical_respiratory_rate_samples;
DROP TABLE canonical_hrv_samples;
DROP TABLE canonical_body_measurements;
DROP TABLE heart_rate_samples;
DROP TABLE respiratory_rate_samples;
DROP TABLE hrv_samples;
DROP TABLE body_measurements;
DROP TABLE cardiovascular_measurements;
DROP TABLE extended_body_measurements;

-- Read-time canonicalization: within each 30-second bin per (metric, context, segment),
-- when two or more providers collide only the best-ranked provider's samples survive;
-- a bin with a single provider passes through untouched. Heart-rate samples taken during
-- sleep use the sleep provider ranking (Withings wins) instead of the heart-rate ranking.
CREATE VIEW canonical_scalar_samples AS
SELECT id,
       source_instance_id,
       ingestion_record_id,
       provider_record_id,
       measured_at,
       metric_type,
       value,
       unit,
       context,
       segment,
       created_at
FROM (
    SELECT s.*,
           COALESCE(pr.rank, 10000) AS provider_rank,
           MIN(COALESCE(pr.rank, 10000)) OVER (
               PARTITION BY s.metric_type,
                            COALESCE(s.context, ''),
                            COALESCE(s.segment, ''),
                            date_bin('30 seconds', s.measured_at, TIMESTAMPTZ 'epoch')
           ) AS best_rank
    FROM scalar_samples s
             JOIN source_instances si ON si.id = s.source_instance_id
             JOIN sources src ON src.id = si.source_id
             JOIN metric_catalog mc ON mc.metric_type = s.metric_type
             LEFT JOIN provider_ranks pr
                       ON pr.provider_code = src.code
                           AND pr.family = CASE
                                               WHEN s.metric_type = 'heart_rate' AND s.context = 'sleep'
                                                   THEN 'sleep'
                                               ELSE mc.family
                                           END
) ranked
WHERE provider_rank = best_rank;

-- Allow the generic scalar ingestion record type alongside the legacy per-family types.
ALTER TABLE ingestion_records
    DROP CONSTRAINT ingestion_records_record_type_check;

ALTER TABLE ingestion_records
    ADD CONSTRAINT ingestion_records_record_type_check
        CHECK (record_type IN (
            'step_interval',
            'sleep_session',
            'body_measurement',
            'heart_rate',
            'activity_summary',
            'sleep_summary',
            'respiratory_rate',
            'hrv',
            'blood_pressure',
            'cardiovascular',
            'extended_body_measurement',
            'scalar'
        ));
