-- Failed post-ingestion derived rebuilds used to be mark-and-log only: the batch kept its
-- error_message but nothing retried the rebuild, so projections stayed stale until a human
-- noticed and ran a replay. This queue records exactly which (source instance, kind, date)
-- rebuilds are owed; a background sweeper retries them with backoff until they succeed.
CREATE TABLE pending_derived_rebuilds
(
    id                 INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_instance_id INTEGER     NOT NULL REFERENCES source_instances (id),
    derived_kind       TEXT        NOT NULL,
    affected_date      DATE        NOT NULL,
    attempts           INTEGER     NOT NULL DEFAULT 0,
    next_attempt_at    TIMESTAMPTZ NOT NULL,
    last_error_message TEXT,
    created_at         TIMESTAMPTZ NOT NULL,
    updated_at         TIMESTAMPTZ NOT NULL,
    UNIQUE (source_instance_id, derived_kind, affected_date),
    CHECK (attempts >= 0)
);

CREATE INDEX pending_derived_rebuilds_due_idx
    ON pending_derived_rebuilds (next_attempt_at);
