CREATE EXTENSION IF NOT EXISTS btree_gist;

CREATE TABLE sources
(
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code         TEXT        NOT NULL UNIQUE,
    display_name TEXT,
    created_at   TIMESTAMPTZ NOT NULL
);

CREATE TABLE source_instances
(
    id                   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_id            INTEGER     NOT NULL REFERENCES sources (id),
    provider_instance_id TEXT        NOT NULL,
    display_name         TEXT,
    created_at           TIMESTAMPTZ NOT NULL,
    updated_at           TIMESTAMPTZ NOT NULL,
    UNIQUE (source_id, provider_instance_id)
);

CREATE TABLE api_clients
(
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         TEXT        NOT NULL UNIQUE,
    api_key_hash TEXT        NOT NULL UNIQUE,
    enabled      BOOLEAN     NOT NULL DEFAULT TRUE,
    created_at   TIMESTAMPTZ NOT NULL,
    last_used_at TIMESTAMPTZ
);

CREATE TABLE ingestion_batches
(
    id                      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_instance_id      INTEGER     NOT NULL REFERENCES source_instances (id),
    batch_external_id       TEXT,
    source_payload_json     JSONB       NOT NULL,
    normalized_payload_json JSONB       NOT NULL,
    status                  TEXT        NOT NULL CHECK (status IN ('received', 'processed', 'failed')),
    ingested_at             TIMESTAMPTZ NOT NULL,
    received_at             TIMESTAMPTZ NOT NULL,
    processed_at            TIMESTAMPTZ,
    error_message           TEXT,
    created_at              TIMESTAMPTZ NOT NULL,
    updated_at              TIMESTAMPTZ NOT NULL
);

CREATE UNIQUE INDEX ingestion_batches_source_instance_batch_external_id_uq
    ON ingestion_batches (source_instance_id, batch_external_id)
    WHERE batch_external_id IS NOT NULL;

CREATE TABLE ingestion_records
(
    id                     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_id               INTEGER     NOT NULL REFERENCES ingestion_batches (id),
    record_type            TEXT        NOT NULL CHECK (record_type IN ('step_interval', 'sleep_session', 'body_measurement', 'heart_rate')),
    provider_record_id     TEXT,
    normalized_record_json JSONB       NOT NULL,
    record_start_at        TIMESTAMPTZ,
    record_end_at          TIMESTAMPTZ,
    created_at             TIMESTAMPTZ NOT NULL
);

CREATE UNIQUE INDEX ingestion_records_batch_provider_record_id_uq
    ON ingestion_records (batch_id, provider_record_id)
    WHERE provider_record_id IS NOT NULL;

CREATE TABLE step_samples
(
    id                  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_instance_id  INTEGER     NOT NULL REFERENCES source_instances (id),
    ingestion_record_id INTEGER REFERENCES ingestion_records (id),
    provider_record_id  TEXT,
    start_at            TIMESTAMPTZ NOT NULL,
    end_at              TIMESTAMPTZ NOT NULL,
    steps               INTEGER     NOT NULL,
    created_at          TIMESTAMPTZ NOT NULL,
    time_range          TSTZRANGE GENERATED ALWAYS AS (tstzrange(start_at, end_at, '[)')) STORED,
    CHECK (start_at < end_at),
    CHECK (steps > 0)
);

CREATE UNIQUE INDEX step_samples_source_instance_provider_record_id_uq
    ON step_samples (source_instance_id, provider_record_id)
    WHERE provider_record_id IS NOT NULL;

CREATE TABLE step_daily_summaries
(
    id                 INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date               DATE        NOT NULL,
    source_instance_id INTEGER     NOT NULL REFERENCES source_instances (id),
    steps              INTEGER     NOT NULL,
    sample_count       INTEGER     NOT NULL,
    computed_at        TIMESTAMPTZ NOT NULL,
    UNIQUE (date, source_instance_id),
    CHECK (steps >= 0),
    CHECK (sample_count > 0)
);

CREATE TABLE sleep_sessions
(
    id                  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_instance_id  INTEGER     NOT NULL REFERENCES source_instances (id),
    ingestion_record_id INTEGER REFERENCES ingestion_records (id),
    provider_record_id  TEXT,
    start_at            TIMESTAMPTZ NOT NULL,
    end_at              TIMESTAMPTZ NOT NULL,
    duration_seconds    BIGINT      NOT NULL,
    created_at          TIMESTAMPTZ NOT NULL,
    CHECK (start_at < end_at),
    CHECK (duration_seconds > 0)
);

CREATE UNIQUE INDEX sleep_sessions_source_instance_provider_record_id_uq
    ON sleep_sessions (source_instance_id, provider_record_id)
    WHERE provider_record_id IS NOT NULL;

CREATE TABLE sleep_stages
(
    id               INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sleep_session_id INTEGER     NOT NULL REFERENCES sleep_sessions (id) ON DELETE CASCADE,
    stage            TEXT        NOT NULL CHECK (stage IN ('awake', 'restless', 'asleep', 'light', 'deep', 'rem', 'unknown')),
    start_at         TIMESTAMPTZ NOT NULL,
    end_at           TIMESTAMPTZ NOT NULL,
    duration_seconds BIGINT      NOT NULL,
    CHECK (start_at < end_at),
    CHECK (duration_seconds > 0)
);

CREATE TABLE body_measurements
(
    id                  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_instance_id  INTEGER          NOT NULL REFERENCES source_instances (id),
    ingestion_record_id INTEGER REFERENCES ingestion_records (id),
    provider_record_id  TEXT,
    measured_at         TIMESTAMPTZ      NOT NULL,
    metric_type         TEXT             NOT NULL CHECK (metric_type IN ('weight', 'body_fat', 'muscle', 'water', 'visceral_fat')),
    value               DOUBLE PRECISION NOT NULL,
    unit                TEXT             NOT NULL,
    created_at          TIMESTAMPTZ      NOT NULL,
    CHECK (
        (metric_type IN ('weight', 'muscle') AND unit = 'kg' AND value > 0)
            OR (metric_type IN ('body_fat', 'water') AND unit = 'percent' AND value >= 0 AND value <= 100)
            OR (metric_type = 'visceral_fat' AND unit = 'rating' AND value > 0)
    )
);

CREATE UNIQUE INDEX body_measurements_source_instance_provider_record_id_metric_type_uq
    ON body_measurements (source_instance_id, provider_record_id, metric_type)
    WHERE provider_record_id IS NOT NULL;

CREATE TABLE heart_rate_samples
(
    id                  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_instance_id  INTEGER     NOT NULL REFERENCES source_instances (id),
    ingestion_record_id INTEGER REFERENCES ingestion_records (id),
    provider_record_id  TEXT,
    measured_at         TIMESTAMPTZ NOT NULL,
    bpm                 INTEGER     NOT NULL,
    context             TEXT,
    created_at          TIMESTAMPTZ NOT NULL,
    CHECK (bpm BETWEEN 25 AND 250),
    CHECK (context IS NULL OR context IN ('resting', 'active', 'workout', 'sleep', 'general', 'unknown'))
);

CREATE UNIQUE INDEX heart_rate_samples_source_instance_provider_record_id_uq
    ON heart_rate_samples (source_instance_id, provider_record_id)
    WHERE provider_record_id IS NOT NULL;

CREATE TABLE provider_oauth_accounts
(
    id                       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider_code            TEXT        NOT NULL,
    provider_user_id         TEXT        NOT NULL,
    provider_instance_id     TEXT        NOT NULL,
    access_token_ciphertext  TEXT        NOT NULL,
    refresh_token_ciphertext TEXT        NOT NULL,
    token_type               TEXT        NOT NULL,
    expires_at               TIMESTAMPTZ NOT NULL,
    scope                    TEXT        NOT NULL,
    created_at               TIMESTAMPTZ NOT NULL,
    updated_at               TIMESTAMPTZ NOT NULL,
    UNIQUE (provider_code, provider_user_id)
);

CREATE TABLE provider_oauth_states
(
    state         TEXT PRIMARY KEY,
    provider_code TEXT        NOT NULL,
    created_at    TIMESTAMPTZ NOT NULL,
    expires_at    TIMESTAMPTZ NOT NULL,
    consumed_at   TIMESTAMPTZ
);

CREATE TABLE provider_sync_runs
(
    id                   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider_code        TEXT        NOT NULL,
    provider_instance_id TEXT        NOT NULL,
    requested_from       TIMESTAMPTZ NOT NULL,
    requested_to         TIMESTAMPTZ NOT NULL,
    status               TEXT        NOT NULL CHECK (status IN ('running', 'processed', 'failed', 'partial_failed')),
    started_at           TIMESTAMPTZ NOT NULL,
    finished_at          TIMESTAMPTZ,
    error_message        TEXT,
    CHECK (requested_from < requested_to)
);

CREATE INDEX step_samples_source_instance_start_end_idx
    ON step_samples (source_instance_id, start_at, end_at);

CREATE INDEX step_samples_start_idx
    ON step_samples (start_at);

CREATE INDEX step_samples_source_instance_time_range_gist_idx
    ON step_samples USING GIST (source_instance_id, time_range);

CREATE INDEX sleep_sessions_source_instance_start_idx
    ON sleep_sessions (source_instance_id, start_at);

CREATE INDEX sleep_sessions_start_end_idx
    ON sleep_sessions (start_at, end_at);

CREATE INDEX sleep_sessions_end_idx
    ON sleep_sessions (end_at);

CREATE INDEX body_measurements_source_instance_metric_measured_idx
    ON body_measurements (source_instance_id, metric_type, measured_at);

CREATE INDEX body_measurements_metric_measured_idx
    ON body_measurements (metric_type, measured_at);

CREATE INDEX heart_rate_samples_source_instance_measured_idx
    ON heart_rate_samples (source_instance_id, measured_at);

CREATE INDEX heart_rate_samples_measured_idx
    ON heart_rate_samples (measured_at);

CREATE INDEX step_daily_summaries_source_instance_date_idx
    ON step_daily_summaries (source_instance_id, date);

CREATE INDEX ingestion_batches_status_received_idx
    ON ingestion_batches (status, received_at);

CREATE INDEX ingestion_records_batch_id_idx
    ON ingestion_records (batch_id);

CREATE INDEX provider_oauth_accounts_provider_instance_idx
    ON provider_oauth_accounts (provider_code, provider_instance_id);

CREATE INDEX provider_sync_runs_provider_instance_started_idx
    ON provider_sync_runs (provider_code, provider_instance_id, started_at);

CREATE INDEX sleep_stages_session_start_idx
    ON sleep_stages (sleep_session_id, start_at);
