ALTER TABLE ingestion_records
    DROP CONSTRAINT ingestion_records_record_type_check;

ALTER TABLE ingestion_records
    ADD CONSTRAINT ingestion_records_record_type_check
        CHECK (record_type IN (
            'step_interval',
            'sleep_session',
            'body_measurement',
            'heart_rate',
            'activity_summary',
            'sleep_summary',
            'respiratory_rate',
            'hrv'
        ));

CREATE TABLE activity_summaries
(
    id                 INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_instance_id INTEGER     NOT NULL REFERENCES source_instances (id),
    ingestion_record_id INTEGER REFERENCES ingestion_records (id),
    provider_record_id TEXT,
    date               DATE        NOT NULL,
    distance_meters    DOUBLE PRECISION,
    active_energy_kcal DOUBLE PRECISION,
    total_energy_kcal  DOUBLE PRECISION,
    elevation_meters   DOUBLE PRECISION,
    soft_minutes       INTEGER,
    moderate_minutes   INTEGER,
    intense_minutes    INTEGER,
    active_minutes     INTEGER,
    avg_heart_rate_bpm INTEGER,
    min_heart_rate_bpm INTEGER,
    max_heart_rate_bpm INTEGER,
    created_at         TIMESTAMPTZ NOT NULL,
    CHECK (
        distance_meters IS NOT NULL
            OR active_energy_kcal IS NOT NULL
            OR total_energy_kcal IS NOT NULL
            OR elevation_meters IS NOT NULL
            OR soft_minutes IS NOT NULL
            OR moderate_minutes IS NOT NULL
            OR intense_minutes IS NOT NULL
            OR active_minutes IS NOT NULL
            OR avg_heart_rate_bpm IS NOT NULL
            OR min_heart_rate_bpm IS NOT NULL
            OR max_heart_rate_bpm IS NOT NULL
    ),
    CHECK (distance_meters IS NULL OR distance_meters >= 0),
    CHECK (active_energy_kcal IS NULL OR active_energy_kcal >= 0),
    CHECK (total_energy_kcal IS NULL OR total_energy_kcal >= 0),
    CHECK (elevation_meters IS NULL OR elevation_meters >= 0),
    CHECK (soft_minutes IS NULL OR soft_minutes >= 0),
    CHECK (moderate_minutes IS NULL OR moderate_minutes >= 0),
    CHECK (intense_minutes IS NULL OR intense_minutes >= 0),
    CHECK (active_minutes IS NULL OR active_minutes >= 0),
    CHECK (avg_heart_rate_bpm IS NULL OR avg_heart_rate_bpm BETWEEN 25 AND 250),
    CHECK (min_heart_rate_bpm IS NULL OR min_heart_rate_bpm BETWEEN 25 AND 250),
    CHECK (max_heart_rate_bpm IS NULL OR max_heart_rate_bpm BETWEEN 25 AND 250)
);

CREATE UNIQUE INDEX activity_summaries_source_instance_provider_record_id_uq
    ON activity_summaries (source_instance_id, provider_record_id)
    WHERE provider_record_id IS NOT NULL;

CREATE TABLE sleep_summaries
(
    id                       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_instance_id       INTEGER     NOT NULL REFERENCES source_instances (id),
    ingestion_record_id      INTEGER REFERENCES ingestion_records (id),
    provider_record_id       TEXT,
    start_at                 TIMESTAMPTZ NOT NULL,
    end_at                   TIMESTAMPTZ NOT NULL,
    time_in_bed_seconds      BIGINT,
    total_sleep_seconds      BIGINT,
    light_sleep_seconds      BIGINT,
    deep_sleep_seconds       BIGINT,
    rem_sleep_seconds        BIGINT,
    sleep_efficiency_percent DOUBLE PRECISION,
    sleep_latency_seconds    BIGINT,
    wakeup_latency_seconds   BIGINT,
    wakeup_duration_seconds  BIGINT,
    wakeup_count             INTEGER,
    waso_seconds             BIGINT,
    sleep_score              INTEGER,
    created_at               TIMESTAMPTZ NOT NULL,
    CHECK (start_at < end_at),
    CHECK (
        time_in_bed_seconds IS NOT NULL
            OR total_sleep_seconds IS NOT NULL
            OR light_sleep_seconds IS NOT NULL
            OR deep_sleep_seconds IS NOT NULL
            OR rem_sleep_seconds IS NOT NULL
            OR sleep_efficiency_percent IS NOT NULL
            OR sleep_latency_seconds IS NOT NULL
            OR wakeup_latency_seconds IS NOT NULL
            OR wakeup_duration_seconds IS NOT NULL
            OR wakeup_count IS NOT NULL
            OR waso_seconds IS NOT NULL
            OR sleep_score IS NOT NULL
    ),
    CHECK (time_in_bed_seconds IS NULL OR time_in_bed_seconds >= 0),
    CHECK (total_sleep_seconds IS NULL OR total_sleep_seconds >= 0),
    CHECK (light_sleep_seconds IS NULL OR light_sleep_seconds >= 0),
    CHECK (deep_sleep_seconds IS NULL OR deep_sleep_seconds >= 0),
    CHECK (rem_sleep_seconds IS NULL OR rem_sleep_seconds >= 0),
    CHECK (sleep_efficiency_percent IS NULL OR sleep_efficiency_percent BETWEEN 0 AND 100),
    CHECK (sleep_latency_seconds IS NULL OR sleep_latency_seconds >= 0),
    CHECK (wakeup_latency_seconds IS NULL OR wakeup_latency_seconds >= 0),
    CHECK (wakeup_duration_seconds IS NULL OR wakeup_duration_seconds >= 0),
    CHECK (wakeup_count IS NULL OR wakeup_count >= 0),
    CHECK (waso_seconds IS NULL OR waso_seconds >= 0),
    CHECK (sleep_score IS NULL OR sleep_score BETWEEN 0 AND 100)
);

CREATE UNIQUE INDEX sleep_summaries_source_instance_provider_record_id_uq
    ON sleep_summaries (source_instance_id, provider_record_id)
    WHERE provider_record_id IS NOT NULL;

CREATE TABLE respiratory_rate_samples
(
    id                  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_instance_id  INTEGER     NOT NULL REFERENCES source_instances (id),
    ingestion_record_id INTEGER REFERENCES ingestion_records (id),
    provider_record_id  TEXT,
    measured_at         TIMESTAMPTZ NOT NULL,
    breaths_per_minute  INTEGER     NOT NULL,
    context             TEXT,
    created_at          TIMESTAMPTZ NOT NULL,
    CHECK (breaths_per_minute BETWEEN 5 AND 80),
    CHECK (context IS NULL OR context IN ('sleep', 'resting', 'general', 'unknown'))
);

CREATE UNIQUE INDEX respiratory_rate_samples_source_instance_provider_record_id_uq
    ON respiratory_rate_samples (source_instance_id, provider_record_id)
    WHERE provider_record_id IS NOT NULL;

CREATE TABLE hrv_samples
(
    id                  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_instance_id  INTEGER          NOT NULL REFERENCES source_instances (id),
    ingestion_record_id INTEGER REFERENCES ingestion_records (id),
    provider_record_id  TEXT,
    measured_at         TIMESTAMPTZ      NOT NULL,
    metric_type         TEXT             NOT NULL,
    value               DOUBLE PRECISION NOT NULL,
    unit                TEXT             NOT NULL,
    context             TEXT,
    created_at          TIMESTAMPTZ      NOT NULL,
    CHECK (metric_type IN ('rmssd')),
    CHECK (unit = 'ms'),
    CHECK (value > 0 AND value <= 500),
    CHECK (context IS NULL OR context IN ('sleep', 'resting', 'general', 'unknown'))
);

CREATE UNIQUE INDEX hrv_samples_source_instance_provider_record_id_metric_type_uq
    ON hrv_samples (source_instance_id, provider_record_id, metric_type)
    WHERE provider_record_id IS NOT NULL;

CREATE INDEX activity_summaries_source_instance_date_idx
    ON activity_summaries (source_instance_id, date);

CREATE INDEX activity_summaries_date_idx
    ON activity_summaries (date);

CREATE INDEX sleep_summaries_source_instance_end_idx
    ON sleep_summaries (source_instance_id, end_at);

CREATE INDEX sleep_summaries_end_idx
    ON sleep_summaries (end_at);

CREATE INDEX respiratory_rate_samples_source_instance_measured_idx
    ON respiratory_rate_samples (source_instance_id, measured_at);

CREATE INDEX respiratory_rate_samples_measured_idx
    ON respiratory_rate_samples (measured_at);

CREATE INDEX hrv_samples_source_instance_metric_measured_idx
    ON hrv_samples (source_instance_id, metric_type, measured_at);

CREATE INDEX hrv_samples_metric_measured_idx
    ON hrv_samples (metric_type, measured_at);
