-- Expand ingestion record types to cover new metric families
ALTER TABLE ingestion_records
    DROP CONSTRAINT ingestion_records_record_type_check;

ALTER TABLE ingestion_records
    ADD CONSTRAINT ingestion_records_record_type_check
        CHECK (record_type IN (
            'step_interval',
            'sleep_session',
            'body_measurement',
            'heart_rate',
            'activity_summary',
            'sleep_summary',
            'respiratory_rate',
            'hrv',
            'blood_pressure',
            'cardiovascular',
            'extended_body_measurement'
        ));

-- Blood pressure measurements: systolic + diastolic as a coherent record
CREATE TABLE blood_pressure_measurements
(
    id                  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_instance_id  INTEGER     NOT NULL REFERENCES source_instances (id),
    ingestion_record_id INTEGER REFERENCES ingestion_records (id),
    provider_record_id  TEXT,
    measured_at         TIMESTAMPTZ NOT NULL,
    systolic_mmhg       INTEGER     NOT NULL,
    diastolic_mmhg      INTEGER     NOT NULL,
    heart_rate_bpm      INTEGER,
    created_at          TIMESTAMPTZ NOT NULL,
    CHECK (systolic_mmhg BETWEEN 60 AND 300),
    CHECK (diastolic_mmhg BETWEEN 30 AND 200),
    CHECK (systolic_mmhg > diastolic_mmhg),
    CHECK (heart_rate_bpm IS NULL OR heart_rate_bpm BETWEEN 25 AND 250)
);

CREATE UNIQUE INDEX blood_pressure_source_instance_provider_record_id_uq
    ON blood_pressure_measurements (source_instance_id, provider_record_id)
    WHERE provider_record_id IS NOT NULL;

CREATE INDEX blood_pressure_source_instance_measured_idx
    ON blood_pressure_measurements (source_instance_id, measured_at);

CREATE INDEX blood_pressure_measured_idx
    ON blood_pressure_measurements (measured_at);

-- Cardiovascular measurements: pulse wave velocity, vascular age, standing HR
CREATE TABLE cardiovascular_measurements
(
    id                  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_instance_id  INTEGER          NOT NULL REFERENCES source_instances (id),
    ingestion_record_id INTEGER REFERENCES ingestion_records (id),
    provider_record_id  TEXT,
    measured_at         TIMESTAMPTZ      NOT NULL,
    metric_type         TEXT             NOT NULL,
    value               DOUBLE PRECISION NOT NULL,
    unit                TEXT             NOT NULL,
    created_at          TIMESTAMPTZ      NOT NULL,
    CHECK (metric_type IN ('pulse_wave_velocity', 'vascular_age', 'standing_heart_rate')),
    CHECK (
        (metric_type = 'pulse_wave_velocity' AND unit = 'm/s' AND value > 0)
        OR (metric_type = 'vascular_age' AND unit = 'years' AND value > 0)
        OR (metric_type = 'standing_heart_rate' AND unit = 'bpm' AND value BETWEEN 25 AND 250)
    )
);

CREATE UNIQUE INDEX cardiovascular_source_instance_provider_id_metric_uq
    ON cardiovascular_measurements (source_instance_id, provider_record_id, metric_type)
    WHERE provider_record_id IS NOT NULL;

CREATE INDEX cardiovascular_source_instance_metric_measured_idx
    ON cardiovascular_measurements (source_instance_id, metric_type, measured_at);

CREATE INDEX cardiovascular_metric_measured_idx
    ON cardiovascular_measurements (metric_type, measured_at);

-- Extended body measurements: fat mass, fat-free mass, bone mass, water compartments, BMR, segmental
CREATE TABLE extended_body_measurements
(
    id                  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_instance_id  INTEGER          NOT NULL REFERENCES source_instances (id),
    ingestion_record_id INTEGER REFERENCES ingestion_records (id),
    provider_record_id  TEXT,
    measured_at         TIMESTAMPTZ      NOT NULL,
    metric_type         TEXT             NOT NULL,
    value               DOUBLE PRECISION NOT NULL,
    unit                TEXT             NOT NULL,
    segment             TEXT,
    created_at          TIMESTAMPTZ      NOT NULL,
    CHECK (metric_type IN (
        'fat_mass',
        'fat_free_mass',
        'bone_mass',
        'intracellular_water',
        'extracellular_water',
        'basal_metabolic_rate',
        'segmental_fat_mass',
        'segmental_muscle_mass',
        'segmental_fat_free_mass'
    )),
    CHECK (segment IS NULL OR segment IN ('left_arm', 'right_arm', 'left_leg', 'right_leg', 'trunk')),
    CHECK (
        (metric_type IN ('fat_mass', 'fat_free_mass', 'bone_mass', 'segmental_fat_mass', 'segmental_muscle_mass', 'segmental_fat_free_mass') AND unit = 'kg' AND value > 0)
        OR (metric_type IN ('intracellular_water', 'extracellular_water') AND unit = 'kg' AND value >= 0)
        OR (metric_type = 'basal_metabolic_rate' AND unit = 'kcal/day' AND value > 0)
    )
);

CREATE UNIQUE INDEX extended_body_measurements_source_instance_provider_metric_seg_uq
    ON extended_body_measurements (source_instance_id, provider_record_id, metric_type, COALESCE(segment, ''))
    WHERE provider_record_id IS NOT NULL;

CREATE INDEX extended_body_measurements_source_instance_metric_measured_idx
    ON extended_body_measurements (source_instance_id, metric_type, measured_at);

CREATE INDEX extended_body_measurements_metric_measured_idx
    ON extended_body_measurements (metric_type, measured_at);

-- Extend sleep summaries with Withings-specific expanded fields
ALTER TABLE sleep_summaries
    ADD COLUMN rem_episodes_count INTEGER,
    ADD COLUMN out_of_bed_count INTEGER,
    ADD COLUMN awake_duration_seconds BIGINT,
    ADD COLUMN overnight_hrv_rmssd DOUBLE PRECISION,
    ADD COLUMN respiratory_rhythm DOUBLE PRECISION,
    ADD COLUMN breathing_quality INTEGER,
    ADD COLUMN snoring_duration_seconds BIGINT,
    ADD COLUMN apnea_hypopnea_index DOUBLE PRECISION,
    ADD COLUMN movement_score DOUBLE PRECISION,
    ADD COLUMN snoring_episode_count INTEGER,
    ADD COLUMN hr_average_bpm INTEGER,
    ADD COLUMN hr_min_bpm INTEGER,
    ADD COLUMN hr_max_bpm INTEGER,
    ADD COLUMN rr_average DOUBLE PRECISION,
    ADD COLUMN rr_min DOUBLE PRECISION,
    ADD COLUMN rr_max DOUBLE PRECISION;

-- New CHECK constraints for nullable expanded fields
ALTER TABLE sleep_summaries
    ADD CHECK (rem_episodes_count IS NULL OR rem_episodes_count >= 0),
    ADD CHECK (out_of_bed_count IS NULL OR out_of_bed_count >= 0),
    ADD CHECK (awake_duration_seconds IS NULL OR awake_duration_seconds >= 0),
    ADD CHECK (overnight_hrv_rmssd IS NULL OR overnight_hrv_rmssd > 0),
    ADD CHECK (breathing_quality IS NULL OR breathing_quality BETWEEN 0 AND 100),
    ADD CHECK (snoring_duration_seconds IS NULL OR snoring_duration_seconds >= 0),
    ADD CHECK (apnea_hypopnea_index IS NULL OR apnea_hypopnea_index >= 0),
    ADD CHECK (movement_score IS NULL OR movement_score >= 0),
    ADD CHECK (snoring_episode_count IS NULL OR snoring_episode_count >= 0),
    ADD CHECK (hr_average_bpm IS NULL OR hr_average_bpm BETWEEN 25 AND 250),
    ADD CHECK (hr_min_bpm IS NULL OR hr_min_bpm BETWEEN 25 AND 250),
    ADD CHECK (hr_max_bpm IS NULL OR hr_max_bpm BETWEEN 25 AND 250),
    ADD CHECK (rr_average IS NULL OR rr_average BETWEEN 5 AND 40),
    ADD CHECK (rr_min IS NULL OR rr_min BETWEEN 5 AND 40),
    ADD CHECK (rr_max IS NULL OR rr_max BETWEEN 5 AND 40);
