CREATE TABLE provider_scheduled_sync_configs
(
    id                   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider_code        TEXT        NOT NULL,
    provider_instance_id TEXT        NOT NULL,
    enabled              BOOLEAN     NOT NULL DEFAULT FALSE,
    data_types           TEXT        NOT NULL,
    cadence_minutes      INTEGER     NOT NULL DEFAULT 1440,
    lookback_days        INTEGER     NOT NULL DEFAULT 7,
    last_successful_from TIMESTAMPTZ,
    last_successful_to   TIMESTAMPTZ,
    last_success_at      TIMESTAMPTZ,
    last_attempted_at    TIMESTAMPTZ,
    failure_count        INTEGER     NOT NULL DEFAULT 0,
    next_run_at          TIMESTAMPTZ,
    last_error_message   TEXT,
    created_at           TIMESTAMPTZ NOT NULL,
    updated_at           TIMESTAMPTZ NOT NULL,
    UNIQUE (provider_code, provider_instance_id),
    CHECK (cadence_minutes BETWEEN 15 AND 43200),
    CHECK (lookback_days BETWEEN 1 AND 31),
    CHECK (failure_count >= 0)
);

CREATE INDEX provider_scheduled_sync_due_idx
    ON provider_scheduled_sync_configs (enabled, next_run_at);

CREATE TABLE provider_scheduled_sync_checkpoints
(
    id                   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    config_id            INTEGER     NOT NULL REFERENCES provider_scheduled_sync_configs (id) ON DELETE CASCADE,
    data_type            TEXT        NOT NULL,
    checkpoint_at        TIMESTAMPTZ,
    last_successful_from TIMESTAMPTZ,
    last_successful_to   TIMESTAMPTZ,
    created_at           TIMESTAMPTZ NOT NULL,
    updated_at           TIMESTAMPTZ NOT NULL,
    UNIQUE (config_id, data_type)
);
