CREATE TABLE sleep_nights
(
    id                 INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date               DATE        NOT NULL,
    timezone           TEXT        NOT NULL,
    source_instance_id INTEGER     NOT NULL REFERENCES source_instances (id),
    sleep_session_id   INTEGER     NOT NULL REFERENCES sleep_sessions (id) ON DELETE CASCADE,
    algorithm_version  INTEGER     NOT NULL,
    computed_at        TIMESTAMPTZ NOT NULL,
    UNIQUE (timezone, sleep_session_id),
    CHECK (timezone <> ''),
    CHECK (algorithm_version > 0)
);

CREATE INDEX sleep_nights_timezone_date_idx
    ON sleep_nights (timezone, date);

CREATE INDEX sleep_nights_source_instance_timezone_date_idx
    ON sleep_nights (source_instance_id, timezone, date);

INSERT INTO sleep_nights (
    date,
    timezone,
    source_instance_id,
    sleep_session_id,
    algorithm_version,
    computed_at
)
SELECT
    (end_at AT TIME ZONE 'UTC')::DATE,
    'Z',
    source_instance_id,
    id,
    1,
    NOW()
FROM sleep_sessions
ON CONFLICT (timezone, sleep_session_id) DO NOTHING;
