CREATE TABLE canonical_heart_rate_samples
(
    id                   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date                 DATE        NOT NULL,
    source_instance_id   INTEGER     NOT NULL REFERENCES source_instances (id),
    heart_rate_sample_id INTEGER     NOT NULL REFERENCES heart_rate_samples (id) ON DELETE CASCADE,
    measured_at          TIMESTAMPTZ NOT NULL,
    context              TEXT        NOT NULL,
    algorithm_version    INTEGER     NOT NULL,
    computed_at          TIMESTAMPTZ NOT NULL,
    UNIQUE (date, heart_rate_sample_id, algorithm_version),
    CHECK (context <> ''),
    CHECK (algorithm_version > 0)
);

CREATE INDEX canonical_heart_rate_samples_date_measured_idx
    ON canonical_heart_rate_samples (date, measured_at);

CREATE INDEX canonical_heart_rate_samples_source_date_idx
    ON canonical_heart_rate_samples (source_instance_id, date);

CREATE TABLE canonical_respiratory_rate_samples
(
    id                         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date                       DATE        NOT NULL,
    source_instance_id         INTEGER     NOT NULL REFERENCES source_instances (id),
    respiratory_rate_sample_id INTEGER     NOT NULL REFERENCES respiratory_rate_samples (id) ON DELETE CASCADE,
    measured_at                TIMESTAMPTZ NOT NULL,
    context                    TEXT        NOT NULL,
    algorithm_version          INTEGER     NOT NULL,
    computed_at                TIMESTAMPTZ NOT NULL,
    UNIQUE (date, respiratory_rate_sample_id, algorithm_version),
    CHECK (context <> ''),
    CHECK (algorithm_version > 0)
);

CREATE INDEX canonical_respiratory_rate_samples_date_measured_idx
    ON canonical_respiratory_rate_samples (date, measured_at);

CREATE INDEX canonical_respiratory_rate_samples_source_date_idx
    ON canonical_respiratory_rate_samples (source_instance_id, date);

CREATE TABLE canonical_hrv_samples
(
    id                INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date              DATE        NOT NULL,
    source_instance_id INTEGER    NOT NULL REFERENCES source_instances (id),
    hrv_sample_id     INTEGER     NOT NULL REFERENCES hrv_samples (id) ON DELETE CASCADE,
    measured_at       TIMESTAMPTZ NOT NULL,
    metric_type       TEXT        NOT NULL,
    context           TEXT        NOT NULL,
    algorithm_version INTEGER     NOT NULL,
    computed_at       TIMESTAMPTZ NOT NULL,
    UNIQUE (date, hrv_sample_id, algorithm_version),
    CHECK (metric_type <> ''),
    CHECK (context <> ''),
    CHECK (algorithm_version > 0)
);

CREATE INDEX canonical_hrv_samples_date_metric_measured_idx
    ON canonical_hrv_samples (date, metric_type, measured_at);

CREATE INDEX canonical_hrv_samples_source_date_metric_idx
    ON canonical_hrv_samples (source_instance_id, date, metric_type);
