CREATE TABLE canonical_sleep_nights
(
    id                 INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date               DATE        NOT NULL,
    timezone           TEXT        NOT NULL,
    source_instance_id INTEGER     NOT NULL REFERENCES source_instances (id),
    sleep_session_id   INTEGER     NOT NULL REFERENCES sleep_sessions (id) ON DELETE CASCADE,
    algorithm_version  INTEGER     NOT NULL,
    computed_at        TIMESTAMPTZ NOT NULL,
    UNIQUE (timezone, sleep_session_id, algorithm_version),
    CHECK (timezone <> ''),
    CHECK (algorithm_version > 0)
);

CREATE INDEX canonical_sleep_nights_timezone_date_idx
    ON canonical_sleep_nights (timezone, date, algorithm_version);

CREATE INDEX canonical_sleep_nights_source_timezone_date_idx
    ON canonical_sleep_nights (source_instance_id, timezone, date, algorithm_version);

CREATE INDEX canonical_heart_rate_samples_algorithm_measured_idx
    ON canonical_heart_rate_samples (algorithm_version, measured_at, heart_rate_sample_id);
