CREATE TABLE canonical_step_samples
(
    id                INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date              DATE        NOT NULL,
    source_instance_id INTEGER    NOT NULL REFERENCES source_instances (id),
    step_sample_id    INTEGER     NOT NULL REFERENCES step_samples (id) ON DELETE CASCADE,
    start_at          TIMESTAMPTZ NOT NULL,
    end_at            TIMESTAMPTZ NOT NULL,
    steps             INTEGER     NOT NULL,
    algorithm_version INTEGER     NOT NULL,
    computed_at       TIMESTAMPTZ NOT NULL,
    UNIQUE (date, step_sample_id, algorithm_version),
    CHECK (steps >= 0),
    CHECK (start_at < end_at),
    CHECK (algorithm_version > 0)
);

CREATE INDEX canonical_step_samples_date_start_idx
    ON canonical_step_samples (date, start_at);

CREATE INDEX canonical_step_samples_source_date_idx
    ON canonical_step_samples (source_instance_id, date);

CREATE TABLE canonical_step_day_bucket_contributions
(
    id                INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date              DATE             NOT NULL,
    source_instance_id INTEGER         NOT NULL REFERENCES source_instances (id),
    step_sample_id    INTEGER          NOT NULL REFERENCES step_samples (id) ON DELETE CASCADE,
    bucket_start_at   TIMESTAMPTZ      NOT NULL,
    bucket_end_at     TIMESTAMPTZ      NOT NULL,
    value             DOUBLE PRECISION NOT NULL,
    algorithm_version INTEGER          NOT NULL,
    computed_at       TIMESTAMPTZ      NOT NULL,
    UNIQUE (date, step_sample_id, bucket_start_at, algorithm_version),
    CHECK (bucket_start_at < bucket_end_at),
    CHECK (value >= 0),
    CHECK (algorithm_version > 0)
);

CREATE INDEX canonical_step_bucket_contributions_bucket_idx
    ON canonical_step_day_bucket_contributions (bucket_start_at, bucket_end_at);

CREATE INDEX canonical_step_bucket_contributions_source_date_idx
    ON canonical_step_day_bucket_contributions (source_instance_id, date);

CREATE TABLE canonical_body_measurements
(
    id                  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date                DATE        NOT NULL,
    source_instance_id  INTEGER     NOT NULL REFERENCES source_instances (id),
    body_measurement_id INTEGER     NOT NULL REFERENCES body_measurements (id) ON DELETE CASCADE,
    measured_at         TIMESTAMPTZ NOT NULL,
    metric_type         TEXT        NOT NULL,
    algorithm_version   INTEGER     NOT NULL,
    computed_at         TIMESTAMPTZ NOT NULL,
    UNIQUE (date, body_measurement_id, algorithm_version),
    CHECK (metric_type <> ''),
    CHECK (algorithm_version > 0)
);

CREATE INDEX canonical_body_measurements_date_metric_measured_idx
    ON canonical_body_measurements (date, metric_type, measured_at);

CREATE INDEX canonical_body_measurements_source_date_metric_idx
    ON canonical_body_measurements (source_instance_id, date, metric_type);
